use_frameworks!
source 'https://github.com/CocoaPods/Specs.git'
target 'FlyUIComponents_Example' do
  pod 'FlyUIComponents', :path => '../'

  target 'FlyUIComponents_Tests' do
    inherit! :search_paths
 pod 'AutoModel'
    pod 'NFAToolkit'
    pod 'SwiftProjects'
    pod 'SnapKit'  , '~> 4.2.0'
#    pod 'SDWebImage'  , '~>  5.5.2'
    pod 'ProThirdpart'

    
  end
end
